name: Daily jobs

on:
  schedule:
    - cron: "0 6 * * *"    # 06:00 МСК
    - cron: "0 14 * * *"   # 14:00 МСК
    - cron: "0 22 * * *"   # 22:00 МСК
  workflow_dispatch:

jobs:
  run-jobs:
    runs-on: ubuntu-latest

    env:
      DRY_RUN: 0  # Добавлено для установки DRY_RUN в 0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run jobs
        run: python runner.py
